<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="Css/Style.css">
    <title>Xsports</title>
</head>

<body>
   
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="home">Xsports</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">

                   

                        <li class="nav-item">
                            <a class="nav-link"  href="home">Home</a>
                        </li>
                 
                        <li class="nav-item">
                            <a class="nav-link"  href="listar">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  href="actividades">Actividades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  href="administrar">Administrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  href="login">Log in</a>
                        </li>

                         <?php if($this->user): ?>
                            <li class="nav-item">
                                <b><a class="nav-link" href="logout">Salir</a></b>
                            </li>
                        <?php endif; ?>
                        <?php if($this->user): ?>
                    <span class="nav-link"><p class="nombre"><?= $this->user->email ?></p></span>
                <?php endif; ?>

                    </ul>
                </div>
            </div>
            </nav>
    </header>

    <main class="container mt-3">
