<?php require 'Templates/Layouts/Header.phtml' ?>



<h1><?=$titulo?></h1>

<ul class="list-group">
<?php foreach($categoria as $cate): ?>
    <li class="list-group-item item-task ">
        <div class="label">
         <a href="categoria/<?=$cate->ID_Categoria?>">   <b> <?= $cate->nombreCate ?></b></a>
      
        <div>
         <img src="<?= $cate->imagen?> " class="img" style="max-width: 290px;"/>
        </div>
        
        </div>
        
        
    </li>
<?php endforeach ?>
</ul>





<?php require 'Templates/Layouts/footer.phtml' ?>
