<?php require 'Templates/Layouts/Header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<h1>REGISTRARSE</h1>
<b>Para acceder y modificar información específica del club es necesario estar registrado en nuestra página</b>
<form method='post' action='login'>
    <div class='form-group'>
        <label for='email'>Email</label>
        <input type='text' class='form-control' id='email' name='email' required>
    </div>
    <div class='form-group'>
        <label for='password'>Password</label>
        <input type='password' class='form-control' id='password' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary'>Login</button>
</form>

<?php require 'Templates/Layouts/footer.phtml' ?>


