<?php require 'Templates/Layouts/Header.phtml' ?>



<h1><?=$titulo?></h1>
<ul class="list-group">
    

<?php foreach($items as $task): ?>

    <li class="list-group-item item-task ">
        <div class="label">
            
        <p>NOMBRE: <?= $task->deporte ?> </p>
        <p>HORARIO: <?= $task->horario ?> </p>
        <p>FECHA: <?= $task->fecha ?> </p>
        <p>PROFESOR: <?= $task->Profesor ?> </p>
        <p>CATEGORIA: <?= $task->nombreCate ?> </p>
        <p>FORMA DE PAGO: <?=$task->formaPago?></p>
        <p>CALIFICACIÓN: <?=$task->Calificación?>✰</p>
        <img src="<?= $task->img?> " class="img" style="max-width: 290px;"/>
        
        </div>
       
    </li>
<?php endforeach ?>
</ul>



<?php require 'Templates/Layouts/footer.phtml' ?>
