<?php require 'Templates/Layouts/Header.phtml' ?>
       <h1><?=$titulo?></h1>

        <div class="label">
          
         <h2><?=$bienvenida?> <?php $tasksnombre ?> <?=$nombre?></h2>
          <img src="img/imgClub.jpg" alt="foto club">
       <p>Bienvenido a la familia Xsports, en esta página encontraras información sobre nosotros y las distintas
        disciplinas deportivas que ofrecemos. </p> 

       <p> Brindamos una atención personalizada y comprometida para cada alumno desde 1989.</p>
       

       <p>Nos encontras en: <b><?=$direccion?></b></p>
       
         </div>
        

<?php require 'Templates/Layouts/footer.phtml' ?>